# server port ?? ??? ??
server:
  port: 8081


# driver config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mcpDB
    username: mcp
    password: mcp
  mail:
    host: smtp.gmail.com
    port: 587
    username: myclassplanner01@gmail.com
    password: iqdzklizxsfnabqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# mybatis ????
mybatis:
  mapper-locations: mappers/*.xml

jwt:
  key: sdfadsfsdfadsfasdfasdfasdfsdfnw4tn23n4on1k5n1k2n14369hn
  time: 86400000
